teams:
  service:
    url: http://teams-service:8080
    timeout:
      connect: 2s
      read: 3s

simulation:
  service:
    url: http://simulation-service:8080
    timeout:
      connect: 2s
      read: 3s

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  devtools:
    restart:
      enabled: true
      poll-interval: 1000
    livereload:
      enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration

match-pool:
  matches-per-pool: 5
  pools-in-advance: 5
  pool-interval-minutes: 3
  schedule-rate-ms: 60000
