name: Run microservices tests

on:
  pull_request:
    branches:
      - main

jobs:
  coupon-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coupon-service
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - run: mvn clean test

  match-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: match-service
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - run: mvn clean test

  odds-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: odds-service
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - run: mvn clean test

  odds-training:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: odds-training
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - run: mvn clean test

  simulation-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: simulation-service
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - run: mvn clean test


  teams-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: teams-service
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - run: mvn clean test